export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SUGGESTIONS = "SET_SUGGESTIONS";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
export const SET_TAB = "SET_TAB";
export const SET_FILTERS = "SET_FILTERS";

export const REQUEST_ALL_GENE_SYMBOLS = 'REQUEST_ALL_GENE_SYMBOLS'
export const RECEIVE_ALL_GENE_SYMBOLS = 'RECEIVE_ALL_GENE_SYMBOLS'

export const REQUEST_QUERY_RESULTS = 'REQUEST_QUERY_RESULTS'
export const RECEIVE_QUERY_RESULTS = 'RECEIVE_QUERY_RESULTS'

export const REQUEST_VARIANT_DETAIL = 'REQUEST_VARIANT_DETAIL'
export const RECEIVE_VARIANT_DETAIL = 'RECEIVE_VARIANT_DETAIL'
